Type: lvgl
OutPut: bin # bin for lv_font_conv's bin output. cfile for lv_font_conv's c file output. dump for lv_font_conv's c file output. headers for generate get text table only.
Command: "node ./node_modules/lv_font_conv/lv_font_conv.js" # command to call converter
Subpixel: H # H for horizontal pixel layout, V for vertical pixel layout, None for disable
UploadCommand: "pio run -t uploadfs" # command to Upload to target
SourcePath: 
GenBashPath:
TemplatePath:
OutputPath: